### ISSUE TITLE
bug when run example echo.py

### ISSUE THREAD

**Issue by thinker007** [deltachat-bot/deltabot-cli-py#4]
#!/usr/bin/env python3
"""Minimal echo-bot example."""
from deltachat2 import MsgData, events
from deltabot_cli import BotCli

cli = BotCli("echobot")

@cli.on(events.RawEvent)
def log_event(bot, accid, event):
    bot.logger.info(event)

@cli.on(events.NewMessage)
def echo(bot, accid, event):
    msg = event.msg
    bot.rpc.send_msg(accid, msg.chat_id, MsgData(text=msg.text))

if __name__ == "__main__":
    cli.start()

run python3 echo.py email  password

then:

python3.12/site-packages/deltachat2/events.py", line 96, in filter
    assert isinstance(event, CoreEvent), "event must be an instance of CoreEvent"
AssertionError: event must be an instance of CoreEvent

**Comment by adbenitez** [comment]
hi, sorry the late reply, this issue was actually fixed in the version 6.1.1 that was released on April 28th 

fixed by 8a3787f7c06ce7a44393cfa77545ab5c1db349e1
